VEHICLE_KEYWORDS = [
    "auto",
    "autos",
    "automobile",
    "carro",
    "carros",
    "vehiculo",
    "vehiculos",
    "año",
    "precio",
    "color",
    "km",
    "marca",
    "modelo",
    "gasolina"
    "electrico"
    "hibrido"
    "kilometraje"
    "combustible"
    "transmision"
    "transmission"
    "automoviles",
    "automobiles",
    "car",
    "vehicle",
    "truck",
    "suv",
    "sedan",
    "hatchback",
    "convertible",
    "price",
    "model",
    "brand",
    "year",
    "mileage",
    "fuel",
    "transmission",
    "toyota",
]
