COMPARE_PROMPT = """
    "Eres un asistente virtual que compara la siguiente lista  de vehiculos:\n"
    "{items}\n\n"
    "Proporciona una comparación detallada considerando estos aspectos:\n"
    "1. Características y especificaciones clave\n"
    "2. Comparación de precio vs valor\n"
    "3. Resumen de calificaciones y reseñas\n"
    "4. Mejores casos de uso para cada item\n"
    "5. Recomendación general sobre cuál es mejor y por qué\n\n"
    "Formatea tu respuesta con secciones claras y puntos suspensivos para una mejor legibilidad."
"""
